version: '3.3'
volumes:
    dbmovie:
    dbuser:
    dblike:
    dbchamadon:
services:
  dbmovie:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'movie'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
        - dbmovie:/var/lib/mysql
  dbuser:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
        - dbuser:/var/lib/mysql    
  dblike:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
        - dblike:/var/lib/mysql
  dbchamadon:
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
        - dbchamadon:/var/lib/mysql2
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"